// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSS00Yery8LOI5IpMcp5KX9xi3zSxewpY',
    appId: '1:357712980558:web:a9db241e2fd1b0b41af11f',
    messagingSenderId: '357712980558',
    projectId: 'emran-wallet-share',
    authDomain: 'emran-wallet-share.firebaseapp.com',
    storageBucket: 'emran-wallet-share.firebasestorage.app',
    measurementId: 'G-Q836X2YD2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZg8WEhsKlvmnNFPlOh3XzabR_X61KsuI',
    appId: '1:357712980558:android:8b5e5272c061b8e51af11f',
    messagingSenderId: '357712980558',
    projectId: 'emran-wallet-share',
    storageBucket: 'emran-wallet-share.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-F4vIv1Q9IwbzSmoEjYBFiRJ28T3C-Gc',
    appId: '1:357712980558:ios:15bb9afcb7dc77591af11f',
    messagingSenderId: '357712980558',
    projectId: 'emran-wallet-share',
    storageBucket: 'emran-wallet-share.firebasestorage.app',
    iosBundleId: 'com.emranuang.emranUang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-F4vIv1Q9IwbzSmoEjYBFiRJ28T3C-Gc',
    appId: '1:357712980558:ios:15bb9afcb7dc77591af11f',
    messagingSenderId: '357712980558',
    projectId: 'emran-wallet-share',
    storageBucket: 'emran-wallet-share.firebasestorage.app',
    iosBundleId: 'com.emranuang.emranUang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSS00Yery8LOI5IpMcp5KX9xi3zSxewpY',
    appId: '1:357712980558:web:e068dd2238c306771af11f',
    messagingSenderId: '357712980558',
    projectId: 'emran-wallet-share',
    authDomain: 'emran-wallet-share.firebaseapp.com',
    storageBucket: 'emran-wallet-share.firebasestorage.app',
    measurementId: 'G-D33B6GBQXK',
  );
}
